4학년2학기(2020)/웹DB프로그래밍/실습/ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [

    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    # 11장 추가
    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete')
]

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

# 9장 추가
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    # auth
    path('accounts/', include('django.contrib.auth.urls')),  # 10장
    path('accounts/register/', UserCreateView.as_view(), name='register'),  # 10장
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),  # 10장

    # shkim
    path('', HomeView.as_view(), name='home'),  ## 127.0.0.1/, 4장 추가
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('namecard/', include('namecard.urls')),
    path('student/', include('student.urls')),
    path('photo/', include('photo.urls')),  # 9장 추가
    path('sugang/', include('sugang.urls')),  # 9장 실습
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 9장 추가

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/urls.py
from django.urls import path
from django.views.generic import ListView, DetailView
from sugang.models import Course, Sugang

# 11/6 실습
from sugang import views


app_name = 'sugang'
urlpatterns = [
    path('', ListView.as_view(model=Course), name='index'),
    path('course/<int:pk>/', DetailView.as_view(model=Course), name='course_detail'),
    path('sugang/<int:pk>/', DetailView.as_view(model=Sugang), name='sugang_detail'),

    # 11/6 실습
    path('course/add/', views.CourseSugangCV.as_view(), name='course_add'),
    path('course/change/', views.CourseChangeLV.as_view(), name='course_change'),
    path('course/<int:pk>/update/', views.CourseSugangUV.as_view(), name='course_update'),
    path('course/<int:pk>/delete/', views.CourseDelV.as_view(), name='course_delete'),
    path('sugang/add/', views.SugangCV.as_view(), name='sugang_add'),
    path('sugang/change/', views.SugangChangeLV.as_view(), name='sugang_change'),
    path('sugang/<int:pk>/update/', views.SugangUV.as_view(), name='sugang_update'),
    path('sugang/<int:pk>/delete/', views.SugangDelV.as_view(), name='sugang_delete'),
]

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/models.py
from django.db import models
from django.urls import reverse


class Course(models.Model):
    title = models.CharField('TITLE', max_length=30)
    professor = models.CharField('PROFESSOR', max_length=30)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('sugang:sugang_detail', args=(self.id,))


class Sugang(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student_id = models.CharField('STUDENT_ID', max_length=30)
    name = models.CharField('NAME', max_length=30)
    create_dt = models.DateTimeField('CREATE_DT', auto_now_add=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        ordering = ('student_id',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('sugang:sugang_detail', args=(self.id,))

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/forms.py
from django.forms import inlineformset_factory
from sugang.models import Course, Sugang


SugangInlineFormSet = inlineformset_factory(Course, Sugang, fields=['student_id', 'name'], extra=2)

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/views.py
from django.views.generic import ListView, DetailView
from sugang.models import Course, Sugang

# 11/6 실습
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from mysite.views import OwnerOnlyMixin
from sugang.forms import SugangInlineFormSet


class SugangCV(LoginRequiredMixin, CreateView):
    model = Sugang
    fields = ('course', 'student_id', 'name')
    success_url = reverse_lazy('sugang:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class SugangChangeLV(LoginRequiredMixin, ListView):
    model = Sugang
    template_name = 'sugang/sugang_change_list.html'

    def get_queryset(self):
        return Sugang.objects.filter(owner=self.request.user)


class SugangUV(OwnerOnlyMixin, UpdateView):
    model = Sugang
    fields = ('course', 'student_id', 'name')
    success_url = reverse_lazy('sugang:index')


class SugangDelV(OwnerOnlyMixin, DeleteView):
    model = Sugang
    success_url = reverse_lazy('sugang:index')


class CourseChangeLV(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'sugang/course_change_list.html'

    def get_queryset(self):
        return Course.objects.filter(owner=self.request.user)


class CourseDelV(OwnerOnlyMixin, DeleteView):
    model = Course
    success_url = reverse_lazy('sugang:index')


class CourseSugangCV(LoginRequiredMixin, CreateView):
    model = Course
    fields = ('title', 'professor')
    success_url = reverse_lazy('sugang:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = SugangInlineFormSet(self.request.POST)
        else:
            context['formset'] = SugangInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for sugangform in formset:
            sugangform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class CourseSugangUV(OwnerOnlyMixin, UpdateView):
    model = Course
    fields = ('title', 'professor')
    success_url = reverse_lazy('sugang:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = SugangInlineFormSet(self.request.POST, instance=self.object)
        else:
            context['formset'] = SugangInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/templates/sugang/course_change_list.html
{% extends "base.html" %}
{% block title %}course_change_list.html{% endblock %}
{% block content %}
    <h1>Course Change - {{user}}</h1>
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr class="table-success">
                <th>Title</th>
                <th>Professor</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.professor }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'sugang:course_update' item.id %}">Update</a></td>
                <td><a href="{% url 'sugang:course_delete' item.id %}">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/templates/sugang/course_confirm_delete.html
{% extends "base.html" %}
{% block title %}course_confirm_delete.html{% endblock %}
{% block content %}
    <h1>Course Delete <small class="font-italic">(including related sugangs)</small></h1>
    <br>

    <form action="." method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/templates/sugang/course_detail.html
{% extends "base.html" %}
{% block title %}course_detail.html{% endblock %}
{% block content %}
    <div class="mt-5">
        <span class="h2">{{ object.title }}</span>
        <span class="h5 font-italic">&nbsp;&nbsp;&nbsp;{{ object.professor }} 교수님</span>
    </div>

    <hr style="margin: 0 0 20px 0;">

    <div class="row">
        <ul>
            {% for sugang in object.sugang_set.all %}
                <li>
                    <a href="{{ sugang.get_absolute_url }}">{{ sugang.student_id }} / {{ sugang.name }} ({{ sugang.create_dt|date:"Y-m-d" }})</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/templates/sugang/course_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}course_form.html{% endblock %}

{% block content %}
    <h1>Course-Sugang Create/Update - {{user}}</h1>
    <p class="font-italic">CourseInlineFormSet을 이용하여 Course를 추가하거나 수정하는 폼입니다.</p>

    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
            {{ form.errors }}
        </div>
    {% endif %}

    {% if formset.errors %}
        <div class="alert alert-warning">
            <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
            {% for formerrors in formset.errors %}
                {{ formerrors }}
            {% endfor %}
        </div>
    {% endif %}

    <form action="." method="post">
        {% csrf_token %}
        <h4>create or update course contents</h4>

        <fieldset class="card pt-3">
            <div class="form-group row">
                {{ form.title|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.title|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.professor|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.professor|add_class:"form-control" }}
                </div>
            </div>
        </fieldset>
        <br>

        <h4>create or update sugang contents</h4>
        <fieldset class="card pt-3">
            {{ formset.management_form }}
            {% for form in formset %}
                {{ form.id }}
                <div class="form-group row">
                    {{ form.student_id|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.student_id|add_class:"form-control" }}
                    </div>
                </div>

                <div class="form-group row">
                    {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.name|add_class:"form-control" }}
                    </div>
                </div>
                <hr>
            {% endfor %}
        </fieldset>

        <div class="form-group card py-1">
            <div class="offset-sm-3 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>
    </form>
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/templates/sugang/course_list.html
{% extends "base.html" %}
{% block title %}course_list.html{% endblock %}
{% block content %}
    {% for object in object_list %}
        <br>
        <a href="{% url 'sugang:course_detail' object.id %}" class="h2">
            {{ object.title }}
        </a>
        <span class="font-italic h5">&nbsp;&nbsp;&nbsp;{{ object.professor }} 교수님</span>

        <hr style="margin: 0 0 20px 0;">

        <div class="row">
            <ul>
                {% for sugang in object.sugang_set.all %}
                    <li>
                        <a href="{{ sugang.get_absolute_url }}">{{ sugang.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/templates/sugang/sugang_change_list.html
{% extends "base.html" %}
{% block title %}sugang_change_list.html{% endblock %}

{% block content %}
    <h1>Sugang Change - {{user}}</h1>
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr class="table-info">
                <th>Course</th>
                <th>Student ID</th>
                <th>Name</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                <tr>
                    <td>{{ item.course }}</td>
                    <td>{{ item.student_id }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'sugang:sugang_update' item.id %}">Update</a></td>
                    <td><a href="{% url 'sugang:sugang_delete' item.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/templates/sugang/sugang_confirm_delete.html
{% extends "base.html" %}
{% block title %}sugang_confirm_delete.html{% endblock %}

{% block content %}
    <h1>Sugang Delete</h1>
    <br>

    <form action="." method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/templates/sugang/sugang_detail.html
{% extends "base.html" %}
{% block title %}sugang_detail.html{% endblock %}
{% block content %}
    <h2 class="mt-5">{{ object.name }}</h2>

    <hr style="margin: 0 0 20px 0;">

    <div class="container">
        <p class="h5">학번: {{ object.student_id }}</p>
        <p class="h5">신청일: {{ object.create_dt }}</p>
        <p class="h5">수강강좌명:
            <a href="{% url 'sugang:course_detail' object.course.id %}">{{ object.course.title }}</a>
        </p>
    </div>
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/실습/ch99/sugang/templates/sugang/sugang_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}sugang_form.html{% endblock %}

{% block content %}
    <h1>Sugang Create/Update - {{user}}</h1>
    <p class="font-italic">수강신청을 생성하거나 수정하는 폼입니다.</p>

    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
            {{ form.errors }}
        </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">
        {% csrf_token %}
        <div class="form-group row">
            {{ form.course|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-2">
                {{ form.course|add_class:"form-control" }}
            </div>
            <div class="col-sm-2 my-auto">
                <a href="{% url 'sugang:course_add' %}" class="btn btn-outline-primary btn-sm">Add Course</a>
            </div>
        </div>

        <div class="form-group row">
            {{ form.student_id|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.student_id|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.name|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.name|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>
    </form>
{% endblock %}