4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/book/urls.py
from django.urls import path
from book.views import BookSearchFormView, BookInsertAndSearchFormView


app_name = 'book'
urlpatterns = [
    # root
    path('', BookSearchFormView.as_view(), name='index'),

    # 내 도서 추가
    path('insert/', BookInsertAndSearchFormView.as_view(), name='insert')
]

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/midterm/urls.py
from django.contrib import admin
from django.urls import path, include
from midterm.views import HomeView


urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # root
    path('', HomeView.as_view(), name='home'),

    # app
    path('book/', include('book.urls')),
    path('mypage/', include('mypage.urls')),
]

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/mypage/urls.py
from django.urls import path
from mypage.views import BookLV, BookDV, TitleSearchFormView, BookAV, BookYAV


app_name = 'mypage'
urlpatterns = [
    # root - 전체 도서 목록
    path('', BookLV.as_view(), name='index'),

    # DetailView - 도서 상세정보
    path('<str:pk>/', BookDV.as_view(), name='detail'),

    # FormView - 제목 검색
    path('search/title/', TitleSearchFormView.as_view(), name='title_search'),

    # ArchiveIndexView - 연도별 검색
    path('archive/year', BookAV.as_view(), name='year_search'),

    # YearArchiveView - 해당 연도의 도서 목록
    path('archive/<int:year>/', BookYAV.as_view(), name='year_archive')
]

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/book/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    isbn = models.CharField('ISBN', max_length=50, primary_key=True)  # ISBN
    title = models.CharField('TITLE', max_length=200)                 # 도서 제목
    author = models.CharField('AUTHOR', max_length=200)               # 저자
    publisher = models.CharField('PUBLISHER', max_length=100)         # 출판사
    pubdate = models.DateField('PUBDATE')                             # 출간일
    price = models.IntegerField('PRICE', default=0)                   # 정가
    description = models.CharField('DESCRIPTION', max_length=1000)    # 줄거리
    image = models.URLField('IMAGE', max_length=200)                  # 썸네일 URL

    class Meta:
        verbose_name = 'Book'
        verbose_name_plural = 'Books'
        ordering = ['isbn']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('mypage:detail', args=(self.isbn,))

    def get_previous(self):
        return self.get_previous_by_isbn()

    def get_next(self):
        return self.get_next_by_isbn()

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/mypage/models.py
# mypage/models.py
# 모델은 book.models의 Book을 공유합니다.

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/book/forms.py
from django import forms


class BookSearchForm(forms.Form):
    keyword = forms.CharField(
        widget = forms.TextInput(attrs={'class':'form-control'}),
        label = '',
    )

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/mypage/forms.py
from django import forms


class TitleSearchForm(forms.Form):
    title = forms.CharField(
        widget = forms.TextInput(attrs={'class': 'form-control'}),
        label = '',
    )

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/book/views.py
from book.models import Book
from book.forms import BookSearchForm
from django.views.generic import FormView, TemplateView
from django.shortcuts import render, redirect
from django.contrib import messages
from urllib import request, parse
from pprint import pprint
import json, re, datetime


class BookSearchFormView(FormView):
    form_class = BookSearchForm
    template_name = 'book/book.html'

    def form_valid(self, form):
        keyword = form.cleaned_data['keyword']
        url = 'https://openapi.naver.com/v1/search/book.json?query=' + parse.quote(keyword) + '&display=30&start=1'

        # 네이버 책 API 호출
        api_request = request.Request(url)
        api_request.add_header('X-Naver-Client-Id', 'qk7TJRGtBZFSBy3pIoIN')
        api_request.add_header('X-Naver-Client-Secret', 'J2IQ57jCr0')
        response = request.urlopen(api_request)

        if response.getcode() == 200:
            body = response.read()
            result = json.loads(body.decode('utf-8'))
            items = result.get('items')
            pprint(items)

            # 문자열에서 HTML 태그 제거
            for item in items:
                item['title'] = removeHtmlTag(item['title'])
                item['author'] = removeHtmlTag(item['author'])
                item['publisher'] = removeHtmlTag(item['publisher'])
                item['description'] = removeHtmlTag(item['description'])

                # 이미지가 없을 경우 대체 이미지 표시
                if item['image'] == '':
                    item['image'] = '/static/img/no-image.png'

            context = {
                'form': form,
                'keyword': keyword,
                'object_list': items,
            }

            return render(self.request, self.template_name, context)
        elif response.getcode() == 400:
            pprint("잘못된 쿼리입니다.")
        elif response.getcode() == 500:
            pprint("네이버 API 서버 오류입니다.")
        else:
            pprint("알 수 없는 에러: %s" % response.getcode())


class BookInsertAndSearchFormView(TemplateView):
    template_name = 'book/book.html'

    # 도서 추가
    def post(self, req):
        try:
            book = Book(
                isbn=req.POST['isbn'],
                title=req.POST['title'],
                author=req.POST['author'],
                publisher=req.POST['publisher'],
                pubdate=datetime.datetime.strptime(req.POST['pubdate'], "%Y%m%d").date(),
                price=req.POST['price'],
                description=req.POST['description'],
                image=req.POST['image'],
            )
            book.save()

            # success message
            messages.info(req, req.POST['title'])
        finally:
            return redirect('/book')


# 문자열에서 HTML 태그 제거
def removeHtmlTag(res):
    return re.sub(re.compile('<.*?>'), '', res)

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/midterm/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/mypage/views.py
from django.views.generic import ListView, DetailView, FormView, ArchiveIndexView, YearArchiveView
from book.models import Book
from mypage.forms import TitleSearchForm
from django.shortcuts import render
from django.db.models import Q


# ListView
class BookLV(ListView):
    model = Book
    template_name = 'mypage/book_list.html'
    paginate_by = 6


# DetailView
class BookDV(DetailView):
    model = Book
    template_name = 'mypage/book_detail.html'


# FormView
class TitleSearchFormView(FormView):
    form_class = TitleSearchForm
    template_name = 'mypage/book_title_search.html'

    def form_valid(self, form):
        title = form.cleaned_data['title']
        book_list = Book.objects.filter(Q(title__icontains=title)).distinct()

        context = {
            'form': form,
            'search_term': title,
            'object_list': book_list
        }

        return render(self.request, self.template_name, context)


# ArchiveIndexView
class BookAV(ArchiveIndexView):
    model = Book
    template_name = 'mypage/book_year_search.html'
    date_field = 'pubdate'
    allow_empty = True


# YearArchiveView
class BookYAV(YearArchiveView):
    model = Book
    template_name = 'mypage/book_archive_year.html'
    date_field = 'pubdate'
    make_object_list = True
    paginate_by = 6

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/book/templates/book/book.html
{% extends 'base.html' %}
{% load static %}
{% block title %}book.html{% endblock %}

{% block extra-style %}
    <style type="text/css">
        {# card hover #}
        .card-img, .card-body {
            opacity: 1;
            display: block;
            width: 100%;
            height: auto;
            transition: .5s ease;
            backface-visibility: hidden;
        }
        .card:hover .card-img, .card:hover .card-body {
            opacity: 0.3;
        }
        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            text-align: center;
        }
        .card:hover .middle{
            opacity: 1;
        }
    </style>
{% endblock %}

{% block content %}
    {# '추가되었습니다' alert #}
    {% if messages %}
        {% for message in messages %}
            {% if message.tag == info %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ message.message }}</strong>이(가) 내 도서에 추가되었습니다!
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    오류가 발생하였습니다.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    {# 도서 검색 form #}
    <form action="" method="post">
        <h5 for="book-search">도서 검색</h5>
        {% csrf_token %}
        {{ form.as_table }}
        <button type="submit" class="btn btn-warning" hidden>검색</button>
        <small id="book-search-desc" class="form-text text-muted">
            제목, 저자, 출판사 검색
        </small>
    </form>

    {# 검색 결과 #}
    {% if object_list %}
        <hr>

        {# 도서 목록 #}
        <div class="row row-cols-2 row-cols-md-3">
            {% for item in object_list %}
                <div class="col mb-3">
                    <div class="card mb-3" style="max-width: 540px; max-height: 200px;">
                        <div class="row no-gutters">
                            {# 썸네일 이미지 #}
                            <div class="col-md-4">
                                <img src="{{ item.image }}" class="card-img" alt="{{ item.isbn }}" style="margin: 0 auto;">
                            </div>

                            {# 제목, 저자, 출판사 정보 #}
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h6 class="card-title">{{ item.title }}</h6>
                                    <p class="card-text text-truncate"><small class="text-muted">{{ item.author }}, {{ item.publisher }}</small></p>
                                </div>
                            </div>

                            {# hover시 '추가' 버튼 표시 #}
                            <div class="middle">
                                <form action="{% url 'book:insert' %}" method="post">
                                    {% csrf_token %}
                                    <input type="text" name="isbn" value="{{ item.isbn }}" hidden>
                                    <input type="text" name="title" value="{{ item.title }}" hidden>
                                    <input type="text" name="author" value="{{ item.author }}" hidden>
                                    <input type="text" name="publisher" value="{{ item.publisher }}" hidden>
                                    <input type="text" name="pubdate" value="{{ item.pubdate }}" hidden>
                                    <input type="text" name="price" value="{{ item.price }}" hidden>
                                    <input type="text" name="description" value="{{ item.description }}" hidden>
                                    <input type="text" name="image" value="{{ item.image }}" hidden>
                                    <button type="submit" class="btn btn-success">추가</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/mypage/templates/mypage/book_archive_year.html
{% extends 'base.html' %}
{% load static %}
{% block title %}book_archive_year.html{% endblock %}

{% block extra-style %}
    <style type="text/css">
        {# 링크 밑줄 제거 #}
        a:hover {
            text-decoration: none;
        }
        {# card hover #}
        .card-img, .card-body {
            opacity: 1;
            display: block;
            width: 100%;
            height: auto;
            transition: .5s ease;
            backface-visibility: hidden;
        }
        .card:hover .card-img, .card:hover .card-body {
            opacity: 0.3;
        }
        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            text-align: center;
        }
        .card:hover .middle{
            opacity: 1;
        }
    </style>
{% endblock %}

{% block content %}
    {# 제목 #}
    <h4>
        <a class="text-success" href="{% url 'mypage:year_search' %}" data-toggle="tooltip" data-placement="bottom" title="연도별 검색" style="color: black">⬅︎</a>&nbsp;&nbsp;
        {{ year|date:"Y" }}년에 출간된 도서
    </h4>

    <hr>

    {# 도서 목록 #}
    {% if object_list %}
        <div class="row row-cols-2 row-cols-md-3">
            {% for item in object_list %}
                <div class="col mb-3">
                    <div class="card mb-3" style="max-width: 540px; max-height: 200px;">
                        <div class="row no-gutters">
                            {# 썸네일 이미지 #}
                            <div class="col-md-4">
                                <img src="{{ item.image }}" class="card-img" alt="{{ item.isbn }}" style="margin: 0 auto;">
                            </div>

                            {# 제목, 저자, 출판사 정보 #}
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h6 class="card-title">{{ item.title }}</h6>
                                    <p class="card-text text-truncate"><small class="text-muted">{{ item.author }}, {{ item.publisher }}</small></p>
                                </div>
                            </div>

                            {# hover시 '추가' 버튼 표시 #}
                            <div class="middle">
                                <a class="btn btn-outline-success" href="{{ item.get_absolute_url }}">상세정보</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        {# 페이지네이션 #}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-end">
                {# 이전 페이지 #}
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link text-success" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled" data-toggle="tooltip" data-placement="bottom" title="첫 페이지입니다">
                        <a class="page-link" href="#">Previous</a>
                    </li>
                {% endif %}

                {# 현재 페이지 of 전체 페이지 #}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="color: black">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                </li>

                {# 다음 페이지 #}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link text-success" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled" data-toggle="tooltip" data-placement="bottom" title="마지막 페이지입니다">
                        <a class="page-link" href="#">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/mypage/templates/mypage/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}book_detail.html{% endblock %}

{% block extra-style %}
    <style type="text/css">
        {# 링크 밑줄 제거 #}
        a:hover {
            text-decoration: none;
        }
        .jumbotron {
            padding: 2rem;
        }
        label {
            color: gray;
        }
        .img-col {
            max-width: 100px;
        }
        .my-col {
            margin-right: 20px;
        }
        .form-control{
            border: 1px solid black;
        }
    </style>
{% endblock %}

{% block content %}
    {# 제목 #}
    <h4>
        {# 뒤로가기 버튼 #}
        <a class="text-success" href="{% url 'mypage:index' %}" data-toggle="tooltip" data-placement="bottom" title="전체 도서" style="color: black">⬅︎</a>&nbsp;&nbsp;
        상세정보
    </h4>

    <hr>

    {# 도서 정보 #}
    <div class="jumbotron">
        <div class="row no-gutters">
            {# 썸네일 #}
            <div class="col img-col">
                <img src="{{ object.image }}" alt="image" class="img-thumbnail">
            </div>

            {# 제목, 저자 #}
            <div class="col">
                <div class="card-body">
                    <h4 class="card-title">{{ object.title }}</h4>
                    <p class="card-text">{{ object.author }}</p>
                </div>
            </div>
        </div>

        <hr>

        <div class="row no-gutters">
            {# 출판사 #}
            <div class="col my-col">
                <label for="publisher">출판사</label>
                <input type="text" class="form-control" id="publisher" value="{{ object.publisher }}" readonly>
            </div>

            {# 출판일 #}
            <div class="col my-col">
                <label for="pubdate">출판일</label>
                <input type="text" class="form-control" id="pubdate" value="{{ object.pubdate }}" readonly>
            </div>
        </div>

        <br>

        <div class="row no-gutters">
            {# ISBN #}
            <div class="col my-col">
                <label for="isbn">ISBN</label>
                <input type="text" class="form-control" id="isbn" value="{{ object.isbn }}" readonly>
            </div>

            {# 정가 #}
            <div class="col my-col">
                <label for="price">정가</label>
                <input type="text" class="form-control" id="price" value="{{ object.price }}원" readonly>
            </div>
        </div>

        <br>

        <div class="row no-gutters">
            {# 설명 #}
            <div class="col my-col">
                <label for="description">설명</label>
                <textarea class="form-control" id="description" rows="3" readonly>{{ object.description }}</textarea>
            </div>
        </div>
    </div>
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/mypage/templates/mypage/book_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}book_list.html{% endblock %}

{% block extra-style %}
    <style type="text/css">
        {# card hover #}
        .card-img, .card-body {
            opacity: 1;
            display: block;
            width: 100%;
            height: auto;
            transition: .5s ease;
            backface-visibility: hidden;
        }
        .card:hover .card-img, .card:hover .card-body {
            opacity: 0.3;
        }
        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            text-align: center;
        }
        .card:hover .middle{
            opacity: 1;
        }
    </style>
{% endblock %}

{% block content %}
    {# 제목 #}
    <h4>내 전체 도서</h4>

    <hr>

    {# 도서 목록 #}
    {% if object_list %}
        <div class="row row-cols-2 row-cols-md-3">
            {% for item in object_list %}
                <div class="col mb-3">
                    <div class="card mb-3" style="max-width: 540px; max-height: 200px;">
                        <div class="row no-gutters">
                            {# 썸네일 이미지 #}
                            <div class="col-md-4">
                                <img src="{{ item.image }}" class="card-img" alt="{{ item.isbn }}" style="margin: 0 auto;">
                            </div>

                            {# 제목, 저자, 출판사 정보 #}
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h6 class="card-title">{{ item.title }}</h6>
                                    <p class="card-text text-truncate"><small class="text-muted">{{ item.author }}, {{ item.publisher }}</small></p>
                                </div>
                            </div>

                            {# hover시 '추가' 버튼 표시 #}
                            <div class="middle">
                                <a class="btn btn-outline-success" href="{{ item.get_absolute_url }}">상세정보</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        {# 페이지네이션 #}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-end">
                {# 이전 페이지 #}
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link text-success" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled" data-toggle="tooltip" data-placement="bottom" title="첫 페이지입니다">
                        <a class="page-link" href="#">Previous</a>
                    </li>
                {% endif %}

                {# 현재 페이지 of 전체 페이지 #}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="color: black">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                </li>

                {# 다음 페이지 #}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link text-success" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled" data-toggle="tooltip" data-placement="bottom" title="마지막 페이지입니다">
                        <a class="page-link" href="#">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <p>검색된 내 도서가 없습니다.</p>
        <p><a href="{% url 'book:index' %}">도서 검색</a>에서 도서를 추가해주세요!</p>
    {% endif %}
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/mypage/templates/mypage/book_year_search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}book_year_search.html{% endblock %}

{% block content %}
    {# 제목 #}
    <h4>연도별 검색</h4>

    <hr>

    {# 데이터가 있을 경우 #}
    {% if date_list %}
        {% for date in date_list %}
            <a class="btn btn-success" href="{% url 'mypage:year_archive' date|date:"Y" %}">{{ date|date:"Y" }}</a>
        {% endfor %}
    {# 데이터가 없을 경우 #}
    {% else %}
        <p>검색된 내 도서가 없습니다.</p>
        <p><a href="{% url 'book:index' %}">도서 검색</a>에서 도서를 추가해주세요!</p>
    {% endif %}
{% endblock %}

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}base.html{% endblock %}</title>

    {# Bootstrap CDN #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <style type="text/css">
        .container {
            padding-top: 20px;
        }
        .footer {
            background: whitesmoke;
            padding-right: 20px;
        }
    </style>

    {# 추가 CSS #}
    {% block extra-style %}{% endblock %}
</head>
<body>
{# 상단 Navbar #}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {# 로고 #}
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'img/logo.png' %}" width="40" height="30" class="d-inline-block align-top" alt="" loading="lazy">
        BookFinder
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    {# 각 App 메뉴 #}
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {# book 앱 #}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'book:index' %}">도서 검색</a>
            </li>

            {# mypage 앱 #}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    내 도서
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'mypage:index' %}">전체 도서</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'mypage:title_search' %}">제목 검색</a>
                    <a class="dropdown-item" href="{% url 'mypage:year_search' %}">연도별 검색</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

{# content #}
<div class="container">
    {% block content %}{% endblock %}
</div>

{# footer #}
<footer class="fixed-bottom bg-info">
    <div class="font-italic text-right footer">2020-2학기 웹DB프로그래밍 / 201533792 유석환 / <a href="https://github.com/youseokhwan/BookFinder" target="_blank">GitHub</a></div>
</footer>

{# Bootstrap CDN #}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

{# Bootstrap 추가 JS #}
<script>
    {# tooltip 초기화 #}
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
</body>
</html>

4학년2학기(2020)/웹DB프로그래밍/중간고사 대체 과제/midterm/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}home.html{% endblock %}

{% block extra-style %}
    <style type="text/css">
        {# 메인 이미지 #}
        .jumbotron {
            background-image: url("{% static 'img/home.jpg' %}");
            background-repeat: no-repeat;
            background-position: center;
            height: 600px;
            color: white;
        }
        .display-5 {
            margin-bottom: 20px;
        }
        .lead {
            background-color: rgba(0, 0, 0, 0.2);
        }
    </style>
{% endblock %}

{% block content %}
    {# 메인 이미지 #}
    <div class="jumbotron">
        <h1 class="display-5">가을은 독서의 계절!</h1>
        <p class="lead">
            등화가친(登火可親). 가을 밤은 시원하고 상쾌하여 등불을 곁에두어 글 읽기에 좋다는 뜻입니다.<br>
            빠르게 달리는 것도 좋지만, 독서를 하며 잠깐 쉬어가는 건 어떨까요?
        </p>
        <hr class="my-4">
        <p>도서를 검색하고 리스트에 추가해보세요!</p>
        <a class="btn btn-warning" href="{% url 'book:index' %}" role="button">도서 검색</a>
        <hr class="my-4">
        <p>내 도서를 확인해보세요!</p>
        <a class="btn btn-warning" href="{% url 'mypage:index' %}" role="button">전체 도서</a>
        <a class="btn btn-warning" href="{% url 'mypage:title_search' %}" role="button">제목 검색</a>
        <a class="btn btn-warning" href="{% url 'mypage:year_search' %}" role="button">연도별 검색</a>
    </div>
{% endblock %}