4학년2학기(2020)/웹DB프로그래밍/실습/ch12/baseball/urls.py
from django.urls import path
from baseball import views


app_name = 'baseball'
urlpatterns = [
    path('', views.TeamLV.as_view(), name='index'),
    path('team/', views.TeamLV.as_view(), name='team_list'),
    path('team/<int:pk>/', views.TeamDV.as_view(), name='team_detail'),
    path('player/<int:pk>/', views.PlayerDV.as_view(), name='player_detail'),

    path('team/add/', views.TeamPlayerCV.as_view(), name='team_add'),
    path('team/change/', views.TeamChangeLV.as_view(), name='team_change'),
    path('team/<int:pk>/update/', views.TeamPlayerUV.as_view(), name='team_update'),
    path('team/<int:pk>/delete/', views.TeamDelV.as_view(), name='team_delete'),
    path('player/add/', views.PlayerCV.as_view(), name='player_add'),
    path('player/change/', views.PlayerChangeLV.as_view(), name='player_change'),
    path('player/<int:pk>/update/', views.PlayerUV.as_view(), name='player_update'),
    path('player/<int:pk>/delete/', views.PlayerDelV.as_view(), name='player_delete'),

    path('team/search/', views.TeamSearchFormView.as_view(), name='team_search'),
    path('player/search/', views.PlayerSearchFormView.as_view(), name='player_search'),
]

4학년2학기(2020)/웹DB프로그래밍/실습/ch12/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('baseball/', include('baseball.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4학년2학기(2020)/웹DB프로그래밍/실습/ch12/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'baseball:index' %}">Baseball</a></li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'baseball:team_add' %}">Team</a>
                    <a class="dropdown-item" href="{% url 'baseball:player_add' %}">Player</a>
                </div>
            </li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Change</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'baseball:team_change' %}">Team</a>
                    <a class="dropdown-item" href="{% url 'baseball:player_change' %}">Player</a>
                </div>
            </li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Search</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'baseball:team_search' %}">Team Search</a>
                    <a class="dropdown-item" href="{% url 'baseball:player_search' %}">Player Search</a>
                </div>
            </li>
        </ul>

        <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
        </form>

        {# 10장 추가 #}
        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                {% if user.is_active %}
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    </div>
                {% else %}
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                    </div>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>


{% block footer %}{% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/c998a172fe.js"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

4학년2학기(2020)/웹DB프로그래밍/실습/ch12/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/lion.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Bookmark App</h3>
            <p>Bookmark is a Uniform Resource Identifier (URI)
                that is stored for later retrieval in any of various storage formats.
                You can store your own bookmarks by Bookmark application.
                It's also possible to update or delete your bookmarks.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages,
                and other media related to its topic.</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by shkim</div>
</footer>
{% endblock %}